#ifndef ENGINE_SHARED_PROTOCOL_EX_H
#define ENGINE_SHARED_PROTOCOL_EX_H

#include <engine/shared/uuid_manager.h>

class CMsgPacker;
class CUnpacker;

enum // NOLINT(readability-enum-initial-value)
{
	NETMSG_EX_INVALID = UUID_INVALID,
	NETMSG_EX_UNKNOWN = UUID_UNKNOWN,

	OFFSET_NETMSG_UUID = OFFSET_UUID,

	__NETMSG_UUID_HELPER = OFFSET_NETMSG_UUID - 1,
#define UUID(id, name) id,
#include "protocol_ex_msgs.h"
#undef UUID
	OFFSET_TEEHISTORIAN_UUID,
};

enum
{
	UNPACKMESSAGE_ERROR = 0,
	UNPACKMESSAGE_OK,
	UNPACKMESSAGE_ANSWER,
};

enum
{
	SERVERCAP_CURVERSION = 6,
	SERVERCAP_LIVEVERSION = 7,
	SERVERCAPFLAG_DDNET = 1 << 0,
	SERVERCAPFLAG_CHATTIMEOUTCODE = 1 << 1,
	SERVERCAPFLAG_ANYPLAYERFLAG = 1 << 2,
	SERVERCAPFLAG_PINGEX = 1 << 3,
	SERVERCAPFLAG_ALLOWDUMMY = 1 << 4,
	SERVERCAPFLAG_SYNCWEAPONINPUT = 1 << 5,
	// Introduced in capabilities version 6. This is only an opt-in
	// negotiation bit; legacy packet layout stays unchanged.
	SERVERCAPFLAG_KCP = 1 << 6,
	SERVERCAPFLAG_LIVE_OBSERVER = 1 << 7,
	SERVERCAPFLAG_LIVE_DIRECTOR = 1 << 8,
	SERVERCAPFLAG_LIVE_REPLAY = 1 << 9,
	SERVERCAP_LIVE_OBSERVER = SERVERCAPFLAG_LIVE_OBSERVER,
	SERVERCAP_LIVE_DIRECTOR = SERVERCAPFLAG_LIVE_DIRECTOR,
	SERVERCAP_LIVE_REPLAY = SERVERCAPFLAG_LIVE_REPLAY,
};

void RegisterUuids(CUuidManager *pManager);
int UnpackMessageId(int *pId, bool *pSys, CUuid *pUuid, CUnpacker *pUnpacker, CMsgPacker *pPacker);

#endif // ENGINE_SHARED_PROTOCOL_EX_H
