[[term]]
source = "Clan"
simplified_chinese = "战队"
traditional_chinese = "戰隊"
korean = "클랜"
japanese = "クラン"
russian = "Клан"
german = "Clan"
spanish = "Clan"
french = "Clan"
brazilian_portuguese = "Clã"
portuguese = "Clã"
turkish = "Klan"
polish = "Klan"

[[term]]
source = "Dummy"
simplified_chinese = "分身"
traditional_chinese = "分身"
korean = "더미"
japanese = "ダミー"
russian = "Дамми"
german = "Dummy"
spanish = "Dummy"
french = "Dummy"
brazilian_portuguese = "Dummy"
portuguese = "Dummy"
turkish = "Dummy"
polish = "Kukła"

[[term]]
source = "Server"
simplified_chinese = "服务器"
traditional_chinese = "伺服器"
korean = "서버"
japanese = "サーバー"
russian = "Сервер"
german = "Server"
spanish = "Servidor"
french = "Serveur"
brazilian_portuguese = "Servidor"
portuguese = "Servidor"
turkish = "Sunucu"
polish = "Serwer"

[[term]]
source = "Map"
simplified_chinese = "地图"
traditional_chinese = "地圖"
korean = "맵"
japanese = "マップ"
russian = "Карта"
german = "Karte"
spanish = "Mapa"
french = "Carte"
brazilian_portuguese = "Mapa"
portuguese = "Mapa"
turkish = "Harita"
polish = "Mapa"

[[term]]
source = "Tencent Cloud"
simplified_chinese = "腾讯云"
traditional_chinese = "騰訊雲"
korean = "텐센트 클라우드"
japanese = "テンセントクラウド"
russian = "Тенсент Клауд"
german = "Tencent Cloud"
spanish = "Tencent Cloud"
french = "Tencent Cloud"
brazilian_portuguese = "Tencent Cloud"
portuguese = "Tencent Cloud"
turkish = "Tencent Cloud"
polish = "Tencent Cloud"

[[term]]
source = "Lyrics"
simplified_chinese = "歌词"
traditional_chinese = "歌詞"
korean = "가사"
japanese = "歌詞"
russian = "Текст песни"
german = "Songtext"
spanish = "Letra"
french = "Paroles"
brazilian_portuguese = "Letra"
portuguese = "Letra"
turkish = "Şarkı sözleri"
polish = "Tekst utworu"

[[term]]
source = "HUD"
simplified_chinese = "HUD"
traditional_chinese = "HUD"
korean = "HUD"
japanese = "HUD"
russian = "HUD"
german = "HUD"
spanish = "HUD"
french = "HUD"
brazilian_portuguese = "HUD"
portuguese = "HUD"
turkish = "HUD"
polish = "HUD"

[[term]]
source = "cache"
simplified_chinese = "缓存"
traditional_chinese = "快取"
korean = "캐시"
japanese = "キャッシュ"
russian = "кэш"
german = "Cache"
spanish = "caché"
french = "cache"
brazilian_portuguese = "cache"
portuguese = "cache"
turkish = "önbellek"
polish = "pamięć podręczna"

[[term]]
source = "source"
simplified_chinese = "来源"
traditional_chinese = "來源"
korean = "소스"
japanese = "ソース"
russian = "источник"
german = "Quelle"
spanish = "fuente"
french = "source"
brazilian_portuguese = "fonte"
portuguese = "fonte"
turkish = "kaynak"
polish = "źródło"

[[term]]
source = "threshold"
simplified_chinese = "阈值"
traditional_chinese = "閾值"
korean = "임계값"
japanese = "しきい値"
russian = "порог"
german = "Schwellwert"
spanish = "umbral"
french = "seuil"
brazilian_portuguese = "limiar"
portuguese = "limiar"
turkish = "eşik"
polish = "próg"

[[term]]
source = "px"
simplified_chinese = "px"
traditional_chinese = "px"
korean = "px"
japanese = "px"
russian = "px"
german = "px"
spanish = "px"
french = "px"
brazilian_portuguese = "px"
portuguese = "px"
turkish = "px"
polish = "px"

[[term]]
source = "ms"
simplified_chinese = "ms"
traditional_chinese = "ms"
korean = "ms"
japanese = "ms"
russian = "ms"
german = "ms"
spanish = "ms"
french = "ms"
brazilian_portuguese = "ms"
portuguese = "ms"
turkish = "ms"
polish = "ms"
