#!/usr/bin/env python3
"""Generate the official DDNet map category registry from ddnet/ddnet-maps."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.request import Request, urlopen


REPOSITORY_TREE_URL = (
    "https://api.github.com/repos/ddnet/ddnet-maps/git/trees/master?recursive=1"
)
ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "src/game/client/components/chat_completion_ddnet_maps.inc"
TYPE_DISPLAY_NAMES = {
    "brutal": "Brutal",
    "ddmax.easy": "DDmaX Easy",
    "ddmax.next": "DDmaX Next",
    "ddmax.nut": "DDmaX Nut",
    "ddmax.pro": "DDmaX Pro",
    "dummy": "Dummy",
    "event": "Event",
    "fun": "Fun",
    "insane": "Insane",
    "moderate": "Moderate",
    "novice": "Novice",
    "oldschool": "Oldschool",
    "race": "Race",
    "solo": "Solo",
}


def fetch_repository_tree() -> dict[str, object]:
    request = Request(
        REPOSITORY_TREE_URL,
        headers={"Accept": "application/vnd.github+json", "User-Agent": "QmClient"},
    )
    with urlopen(request, timeout=30) as response:
        return json.load(response)


def collect_map_categories(tree: dict[str, object]) -> dict[str, str]:
    if tree.get("truncated"):
        raise RuntimeError("GitHub returned a truncated ddnet-maps tree")

    categories: dict[str, str] = {}
    seen_types: set[str] = set()
    for entry in tree.get("tree", []):
        if not isinstance(entry, dict):
            continue
        path = entry.get("path")
        if not isinstance(path, str) or not path.endswith(".map"):
            continue
        parts = path.split("/")
        if len(parts) != 4 or parts[0] != "types" or parts[2] != "maps":
            continue
        type_name = parts[1]
        if type_name not in TYPE_DISPLAY_NAMES:
            raise RuntimeError(f"Unknown ddnet-maps type directory: {type_name}")
        map_name = parts[3][:-4]
        previous = categories.get(map_name)
        category = TYPE_DISPLAY_NAMES[type_name]
        if previous is not None and previous != category:
            raise RuntimeError(
                f"Map {map_name!r} occurs in both {previous!r} and {category!r}"
            )
        categories[map_name] = category
        seen_types.add(type_name)

    missing_types = TYPE_DISPLAY_NAMES.keys() - seen_types
    if missing_types:
        raise RuntimeError(
            f"Missing expected ddnet-maps types: {', '.join(sorted(missing_types))}"
        )
    if len(categories) < 2000:
        raise RuntimeError(
            f"Unexpectedly small ddnet-maps registry: {len(categories)} maps"
        )
    return categories


def render_registry(categories: dict[str, str], tree_sha: str) -> str:
    lines = [
        "// Generated by qmclient_scripts/update_ddnet_map_categories.py.",
        f"// Source: ddnet/ddnet-maps tree {tree_sha}",
        "// Do not edit manually.",
    ]
    for map_name in sorted(categories, key=lambda value: (value.casefold(), value)):
        encoded_name = json.dumps(map_name, ensure_ascii=False)
        encoded_category = json.dumps(categories[map_name], ensure_ascii=False)
        lines.append(f"\t{{{encoded_name}, {encoded_category}}},")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Only verify generated output"
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    tree = fetch_repository_tree()
    categories = collect_map_categories(tree)
    output = render_registry(categories, str(tree.get("sha", "unknown")))
    if args.check:
        if (
            not args.output.exists()
            or args.output.read_text(encoding="utf-8") != output
        ):
            raise SystemExit(f"Outdated generated registry: {args.output}")
    else:
        args.output.write_text(output, encoding="utf-8", newline="\n")
    print(f"DDNet map categories: {len(categories)} maps -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
